version: "3.7"

services:
  db:
    image: postgres:10.7
    environment:
      POSTGRES_DB: rating_dev
      POSTGRES_USER: rating
      POSTGRES_PASSWORD: rating
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
