version: "3.7"

services:
  web:
    build: .
    command: gunicorn rating.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/src/rating/static
    expose:
      - 8000
    env_file: .env.web
    depends_on:
      - db
  db:
    image: postgres:10.7
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

  nginx:
    image: nginx:1.16.0
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/src/rating/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  prod_postgres_data:
  static_volume:
