# Generated by Django 2.2.4 on 2019-08-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20190723_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Revision')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.University')),
            ],
        ),
    ]
