# Generated by Django 2.2.4 on 2019-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'configuration', 'verbose_name_plural': 'configurations'},
        ),
        migrations.AddField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
