# Generated by Django 2.2.4 on 2019-08-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190723_1941'),
        ('user_site', '0002_auto_20190803_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('university', 'revision')},
        ),
    ]
