# Generated by Django 2.2.3 on 2019-07-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopus', models.BooleanField(default=False, verbose_name='Scopus')),
                ('google_scholar', models.BooleanField(default=False, verbose_name='Google Scholar')),
                ('semantic_scholar', models.BooleanField(default=False, verbose_name='Semantic Scholar')),
                ('wos', models.BooleanField(default=False, verbose_name='Web of Science')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1024)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='ORCID')),
                ('scopus_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Scopus Key')),
                ('google_scholar_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Google Scholar Key')),
                ('semantic_scholar_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Semantic Scholar Key')),
                ('wos_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Web of Science Key')),
                ('articles', models.ManyToManyField(through='core.ArticleItem', to='core.Article')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University')),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faculty'),
        ),
        migrations.AddField(
            model_name='articleitem',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='persons',
            field=models.ManyToManyField(through='core.ArticleItem', to='core.Person'),
        ),
        migrations.CreateModel(
            name='WosSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revision')),
            ],
            options={
                'verbose_name': 'Web of Science Snapshot',
                'verbose_name_plural': 'Web of Science Snapshots',
                'abstract': False,
                'unique_together': {('revision', 'person')},
            },
        ),
        migrations.CreateModel(
            name='SemanticScholarSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_velocity', models.PositiveIntegerField(default=0)),
                ('influential_citation_count', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revision')),
            ],
            options={
                'verbose_name': 'Semantic Scholar Snapshot',
                'verbose_name_plural': 'Semantic Scholar Snapshots',
                'abstract': False,
                'unique_together': {('revision', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ScopusSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_index', models.PositiveIntegerField(default=0, verbose_name=' h-index')),
                ('documents', models.PositiveIntegerField(default=0)),
                ('citations', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revision')),
            ],
            options={
                'verbose_name': 'Scopus Snapshot',
                'verbose_name_plural': 'Scopus Snapshots',
                'abstract': False,
                'unique_together': {('revision', 'person')},
            },
        ),
        migrations.CreateModel(
            name='GoogleScholarSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_index', models.PositiveIntegerField(default=0, verbose_name=' h-index')),
                ('citations', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revision')),
            ],
            options={
                'verbose_name': 'Google Scholar Snapshot',
                'verbose_name_plural': 'Google Scholar Snapshots',
                'abstract': False,
                'unique_together': {('revision', 'person')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='articleitem',
            unique_together={('article', 'person')},
        ),
    ]
