# Generated by Django 2.2.3 on 2019-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190713_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_types',
            field=models.ManyToManyField(related_name='persons', to='core.PersonType'),
        ),
    ]
