# Generated by Django 2.2.3 on 2019-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190713_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_types',
            field=models.ManyToManyField(blank=True, related_name='persons', to='core.PersonType'),
        ),
    ]
