# Generated by Django 2.2.4 on 2019-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_revision_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='source',
            field=models.CharField(blank=True, choices=[('imported', 'Import')], max_length=30),
        ),
    ]
